# Generated by Django 5.2.15 on 2026-06-16 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('slug', models.SlugField(unique=True, verbose_name='สลัก (URL Slug)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา (บาท)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
                ('is_active', models.BooleanField(default=True, verbose_name='แสดงบนหน้าเว็บ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้าหน้าเว็บ',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่สำหรับจัดส่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ข้อมูลลูกค้า',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบสั่งซื้อ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ยอดสุทธิ')),
                ('status', models.CharField(choices=[('pending', 'รอการชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('processing', 'กำลังจัดเตรียมสินค้า'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิกคำสั่งซื้อ')], default='pending', max_length=20, verbose_name='สถานะใบสั่งซื้อ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่งซื้อ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='storefront.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'รายการคำสั่งซื้อ',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา ณ วันสั่งซื้อ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='storefront.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในคำสั่งซื้อ',
                'verbose_name_plural': 'รายการสินค้าในคำสั่งซื้อ',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='คะแนน')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='ความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='storefront.customer', verbose_name='ลูกค้า')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='storefront.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รีวิวสินค้า',
                'verbose_name_plural': 'รีวิวสินค้า',
                'unique_together': {('product', 'customer')},
            },
        ),
    ]
