# Generated by Django 5.2.15 on 2026-06-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อแคมเปญการตลาด')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดแคมเปญ')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='ภาพแบนเนอร์แคมเปญ')),
                ('start_date', models.DateTimeField(verbose_name='วันที่เริ่มแคมเปญ')),
                ('end_date', models.DateTimeField(verbose_name='วันที่สิ้นสุดแคมเปญ')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะแคมเปญ (ใช้งาน/ปิดใช้งาน)')),
            ],
            options={
                'verbose_name': 'แคมเปญการตลาด',
                'verbose_name_plural': 'แคมเปญการตลาด (Campaigns)',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสคูปอง')),
                ('coupon_type', models.CharField(choices=[('percentage', 'ลดเป็นเปอร์เซ็นต์ (%)'), ('fixed', 'ลดเป็นจำนวนเงินสุทธิ (บาท)'), ('free_shipping', 'คูปองส่งฟรี')], default='fixed', max_length=20, verbose_name='ประเภทส่วนลด')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='มูลค่าส่วนลด (บาท หรือ %)')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ส่วนลดสูงสุด (เฉพาะแบบ %)')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ยอดสั่งซื้อขั้นต่ำ (บาท)')),
                ('usage_limit', models.PositiveIntegerField(default=100, verbose_name='จำนวนสิทธิ์การใช้รวม')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนที่ใช้ไปแล้ว')),
                ('start_date', models.DateTimeField(verbose_name='วันที่เริ่มใช้งาน')),
                ('end_date', models.DateTimeField(verbose_name='วันที่หมดอายุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งานคูปอง')),
            ],
            options={
                'verbose_name': 'คูปองส่วนลด',
                'verbose_name_plural': 'ข้อมูลคูปองส่วนลด',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='คะแนนสะสมคงเหลือ')),
                ('accumulated_points', models.IntegerField(default=0, verbose_name='คะแนนสะสมทั้งหมดที่เคยได้รับ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุดเมื่อ')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_points', to='storefront.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'คะแนนสะสมลูกค้า',
                'verbose_name_plural': 'คะแนนสะสมของลูกค้า (Loyalty Points)',
            },
        ),
    ]
