# Generated by Django 5.2.15 on 2026-06-16 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storefront', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อผู้จำหน่าย/ซัพพลายเออร์')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ผู้ติดต่อ')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
            ],
            options={
                'verbose_name': 'ผู้จำหน่ายสินค้า (Supplier)',
                'verbose_name_plural': 'ข้อมูลผู้จำหน่ายสินค้า (Suppliers)',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100, unique=True, verbose_name='รหัส SKU')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='สี')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='ขนาด')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='บาร์โค้ด')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาทุน (บาท)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='storefront.product', verbose_name='สินค้าหน้าเว็บ')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skus', to='inventory.supplier', verbose_name='ผู้จัดจำหน่าย')),
            ],
            options={
                'verbose_name': 'รหัสสินค้าคลัง (SKU)',
                'verbose_name_plural': 'รหัสสินค้าคลัง (SKUs)',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่งจัดวาง (Zone/Aisle/Shelf)')),
                ('reorder_level', models.PositiveIntegerField(default=10, verbose_name='ระดับเตือนสต็อกต่ำ')),
                ('last_counted_date', models.DateTimeField(auto_now=True, verbose_name='วันที่ตรวจสอบล่าสุด')),
                ('sku', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.sku', verbose_name='สินค้า SKU')),
            ],
            options={
                'verbose_name': 'จำนวนสินค้าคงคลัง',
                'verbose_name_plural': 'รายการสินค้าคงคลัง (Stock)',
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('inbound', 'รับสินค้าเข้าคลัง (Inbound)'), ('outbound', 'จ่ายสินค้าออก (Outbound)'), ('audit', 'การตรวจนับคลัง (Audit Adjustment)'), ('damaged', 'สินค้าชำรุดเสียหาย (Damaged)'), ('returned', 'ลูกค้ารับคืนเข้าระบบ (Returned)')], max_length=20, verbose_name='ประเภทการปรับปรุง')),
                ('quantity_changed', models.IntegerField(verbose_name='จำนวนที่ปรับปรุง (+/-)')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลและรายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่ทำรายการ')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.sku', verbose_name='สินค้า SKU')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทำรายการ')),
            ],
            options={
                'verbose_name': 'ประวัติการปรับปรุงสต็อก',
                'verbose_name_plural': 'ประวัติการปรับปรุงสต็อก (Stock Adjustments)',
            },
        ),
    ]
