# Generated by Django 5.2.15 on 2026-06-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ผู้บริการขนส่ง (เช่น Flash, Kerry)')),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='ค่าจัดส่งเริ่มต้น (บาท)')),
                ('weight_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='น้ำหนักสูงสุดที่รับได้ (กก.)')),
                ('estimated_days', models.CharField(max_length=50, verbose_name='ระยะเวลาจัดส่งโดยประมาณ (วัน)')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้บริการ')),
            ],
            options={
                'verbose_name': 'วิธีการจัดส่ง',
                'verbose_name_plural': 'ผู้บริการขนส่งสินค้า',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='เหตุผลและคำอธิบายการคืน')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบคำขอ (Pending)'), ('approved', 'อนุมัติการคืนสินค้า (Approved)'), ('received', 'ได้รับพัสดุคืนแล้ว (Received)'), ('rejected', 'ปฏิเสธคำขอคืน (Rejected)')], default='pending', max_length=20, verbose_name='สถานะการคืนสินค้า')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขส่งคืนพัสดุของลูกค้า')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาขอคืนสินค้า')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาดำเนินการสิ้นสุด')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='storefront.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'รายการคืนสินค้า',
                'verbose_name_plural': 'รายการขอคืนสินค้า (Returns)',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='เลขติดตามพัสดุ (Tracking Number)')),
                ('status', models.CharField(choices=[('pending', 'รอจัดส่ง (Pending)'), ('in_transit', 'อยู่ระหว่างการขนส่ง (In Transit)'), ('out_for_delivery', 'พัสดุอยู่ระหว่างนำจ่าย (Out for Delivery)'), ('delivered', 'จัดส่งเรียบร้อยแล้ว (Delivered)'), ('failed', 'การจัดส่งล้มเหลว/ติดต่อไม่ได้ (Failed)'), ('returned', 'พัสดุตีกลับต้นทาง (Returned)')], default='pending', max_length=25, verbose_name='สถานะการนำส่งพัสดุ')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='ชื่อผู้รับปลายทาง')),
                ('recipient_phone', models.CharField(max_length=50, verbose_name='เบอร์โทรศัพท์ติดต่อ')),
                ('shipping_address', models.TextField(verbose_name='ที่อยู่จัดส่งจริง')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาส่งออกจากคลัง')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาจัดส่งสำเร็จ')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='อัปเดตสถานะล่าสุด')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='storefront.order', verbose_name='คำสั่งซื้อ')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistics.shippingmethod', verbose_name='วิธีการจัดส่ง')),
            ],
            options={
                'verbose_name': 'ข้อมูลการจัดส่งสินค้า',
                'verbose_name_plural': 'ข้อมูลการจัดส่งสินค้า (Deliveries)',
            },
        ),
    ]
